### ISSUE TITLE
jekyll folder (opened in VSCode) Ruby version doesn't match Home Terminal 

### ISSUE THREAD

**Issue by juliajoo** [monfresh/laptop#69] opened 2021-01-27 22:27 UTC
Hi! Monfresh!
First of all, thank you very much for this resourceful script that you wrote. 
Thanks to you, I have a ruby 2.7.2. clean and running well. I deleted rbenv and ran your script, and I confirmed that I got the message 'All is done' at the end of the process. 

However when I go into the directory of my jekyll project (which I am struggling to host it via Netlify), my ruby version is still `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`, whereas when I run `ruby -v` in my Terminal app, it returns `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`.

This is being my biggest problem, because this is causing me a serial bugs and problems...
What I eventually am trying to do is `bundle exec jekyll serve` in my jekyll directory. However when I run this, I run into this Error -> `jekyll 3.8.7 | Error:  No such file or directory @ rb_sysopen - /Users/Jjoo/Downloads/youngdesign-master/bin/gulp`
And when I seek to solve this error by (I am not sure if I am going the right thing, maybe you can also give me a wise advice on this matter as well) uninstalling jekyll 3.8.5. and reinstalling jekyll 3.8.7. (<- I am assuming this because in my Gemfile, I see this `gem "jekyll", "~> 3.8.5"`. Am I doing the right thing..?) And when I try to go 'gem uninstall jekyll', this returns me another error of this..
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.`

This is really driving me crazy..
Could you please help me solve this serial train of errors?

Below, I attached my laptop.log file. Hope to hear back from you soon. 
`
[laptop.log](https://github.com/monfresh/laptop/files/5883447/laptop.log)
`

**Comment by juliajoo** [comment] 2021-01-27 22:41
Oh, and I tried to run chruby 2.7.2. in my jekyll folder to change the version of the ruby to 2.7.2. but then I get this message
`bash: chruby: command not found`
But in my Terminal(~zsh),if I run `chruby --version`,  I get `chruby: 0.3.9,` which I think chruby is installed in my computer.

**Comment by monfresh** [comment] 2021-01-28 01:33
Hi @juliajoo. This is not an issue with my script, but I will help you. As you noticed, things are working in your Terminal, which should tell you that something must be wrong with your VSCode setup. How would you test this theory? One way would be to run `bundle exec jekyll serve` from within your directory in the terminal, not in VSCode. Here's how to do that:
1. Launch Terminal
2. `cd` into your jekyll directory
3. run `chruby 2.7.2`
4. run `bundle install` to make sure you have all the required gems from the Gemfile
5. run `bundle exec jekyll serve` 
If that works, or if you see a different error than in VSCode, then you know it's something in VSCode that is the issue.

If you look closely, you'll notice that VSCode mentioned `bash`, which is a different shell than the one in your Terminal, which is `zsh` as you mentioned. If you're not familiar with shells and why `bash` in VSCode would be different from `zsh` in Terminal, read this: https://www.moncefbelyamani.com/which-shell-am-i-using-how-can-i-switch/

By default, VSCode uses the same shell as your Terminal, but perhaps at some point you changed it? In any case, you should see a dropdown in the VSCode terminal that will show something like `1: bash`. Click on it, and then select "Select Default Shell", like in this screenshot:

<img width="399" alt="Screen Shot 2021-01-27 at 8 23 11 PM" src="https://user-images.githubusercontent.com/811150/106076531-b7a4c580-60dd-11eb-8cb7-fd5f56448b4f.png">

Then, choose `zsh bin/zsh` from the list, and quit and restart VSCode. You should now see `1: zsh` in your VSCode terminal, and `ruby -v` should show `2.7.2`.

Also, make sure to read this section, and the part about setting a `.ruby-version` file in particular, so that you always have the right version of Ruby when you're inside your Jekyll directory:
https://github.com/monfresh/laptop#how-to-switch-between-ruby-versions-and-install-different-versions

**Comment by juliajoo** [comment] 2021-01-28 11:41
Thank you, Monfresh! Trying that restored my VSCode Terminal back to zsh and using ruby 2.7.2
While following your instruction, I just realized that I ran your script with my Catalina not up to date(mine was 10.15.6 but the latest one was 10.15.7 I guess). In this case, do I have to delete your script and rerun everything or can I just run `laptop` in my Terminal? 

And after running your script, I `bundle exec jekyll serve` command is not working in both (1) my local git repository and (2) fresh clone of that repository. Below is what I get when I run bundle exec jekyll serve in my vscode terminal. I checked the version of the ruby inside my directory as well and it was  `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]` and I also ran `chruby 2.7.2` in that project directory. Do you see what is happening and what I can do to solve this issue? Your comment would be very much appreciated. 

Jjoo@bagjuyeonguimbp youngdesign % bundle exec jekyll serve
Could not find public_suffix-3.0.3 in any of the sources
Run `bundle install` to install missing gems.
Jjoo@bagjuyeonguimbp youngdesign % bundle install
dyld: lazy symbol binding failed: Symbol not found: _rb_deprecate_constant
  Referenced from: /Users/Jjoo/.gem/ruby/2.7.2/gems/etc-1.2.0/lib/etc.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_deprecate_constant
  Referenced from: /Users/Jjoo/.gem/ruby/2.7.2/gems/etc-1.2.0/lib/etc.bundle
  Expected in: flat namespace

zsh: abort      bundle install

**Comment by monfresh** [comment] 2021-01-30 00:43
It's very possible that the error could be due to your outdated command line tools. This is why in the instructions for this script I say that the first thing you should do is make sure your system is up to date. You don't have to delete my script. Update to 10.15.7 and any other Catalina updates. Also, it looks like you have Xcode installed. If the only reason you installed it was because you thought you needed it for Ruby development, you can remove it from your Applications and empty the trash. All you need are the standalone command line tools. 

Then restart your computer, and see if Homebrew is still complaining about missing or out of date command line tools:

```sh
brew doctor
```

If it is, follow Homebrew's instructions. It will say something like this:
```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

Once the command line tools are installed, you'll need to uninstall Ruby and reinstall it with my script:

```shell
rm -rf ~/.rubies/
```
If it says "permission denied", try it with `sudo`:
```shell
sudo rm -rf ~/.rubies/
```
Then run my script again:
```shell
laptop
```

**Comment by juliajoo** [comment] 2021-01-30 16:32
Hi monfresh.
As you advised, I ran `brew doctor` and as you assumed, I ran into those texts. So I updated the software and deleted rubies file, quit terminal and restarted terminal, and ran your script. 
But I think the script failed and I think it only downloaded ruby 3.0.0, even though I think I need ruby 2.7.2. to execute jekyll file safely in my laptop(right?). 
I attached the laptop.log file in this comment. 
[laptop.log](https://github.com/monfresh/laptop/files/5898295/laptop.log)

**Comment by monfresh** [comment] 2021-01-30 17:35
It looks like you still need the command line tools. Can you try these steps please?

1. Remove command line tools:
```sh
sudo rm -rf /Library/Developer/CommandLineTools
```

2. Re-install them:
```sh
sudo xcode-select --install
```

3. Point the tools to the right directory:
```sh
xcode-select -s  /Library/Developer/CommandLineTools
```

4. Restart your computer
5. Verify that the command line tools are in the right place:
```sh
xcode-select -p
```
It should say `/Library/Developer/CommandLineTools`. If not, repeat step 3.
6. Remove ruby and node from Homebrew:
```sh
brew uninstall --ignore-dependencies ruby node yarn nodenv
```
7. Clean up Homebrew:
```sh
brew cleanup
```
8. Remove Ruby:
```sh
rm -rf ~/.rubies
```
9. Run my script again:
```sh
laptop
```

**Comment by juliajoo** [comment] 2021-01-30 19:18
Thank you so much! I followed your instruction and now I think it is half succeeded.
I think it succeeded in installing ruby 2.7.2 but it failed in updating rubygems. These are the end part of the responses that I got from terminal after running `laptop`. I also attached the entire log in laptop.log file. 
![image](https://user-images.githubusercontent.com/22519671/106365800-3a28c180-6338-11eb-9c5b-1466c0f2d8b1.png)
[laptop.log](https://github.com/monfresh/laptop/files/5898570/laptop.log)

**Comment by monfresh** [comment] 2021-01-30 19:55
We're making progress, but Homebrew is still complaining about some things. Let's see if we can take care of them:

```sh
brew link --overwrite git
brew link --overwrite node
rm /usr/local/lib/libavcodec.56.dylib
rm /usr/local/lib/libavformat.56.dylib
rm /usr/local/lib/libavutil.54.dylib
rm /usr/local/lib/libswresample.1.dylib
brew upgrade
```
Then run `brew doctor` and paste the output here please.

**Comment by juliajoo** [comment] 2021-01-30 21:09
Okay. 
`brew link --overwrite git` worked but the second line didn't work so far. Here is what I've got.

```
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew link --overwrite git
Linking /usr/local/Cellar/git/2.30.0... 210 symlinks created.
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew link --overwrite node
Linking /usr/local/Cellar/node/15.7.0... 
Error: Could not symlink include/node/cppgc/allocation.h
/usr/local/include/node/cppgc is not writable.
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew link --overwrite node
Linking /usr/local/Cellar/node/15.7.0... 
Error: Could not symlink include/node/cppgc/allocation.h
/usr/local/include/node/cppgc is not writable.
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % 
```

**Comment by monfresh** [comment] 2021-01-30 21:17
OK, try this:

```sh
brew uninstall --ignore-dependencies node yarn nodenv
sudo rm -rf /usr/local/include/node
```
Then the rest of the steps from my previous message.

**Comment by juliajoo** [comment] 2021-01-30 22:06
I ran the command and now I get this error message..
```
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew uninstall --ignore-dependencies node yarn nodenv
Uninstalling /usr/local/Cellar/node/15.7.0... (3,298 files, 55.6MB)
Uninstalling /usr/local/Cellar/yarn/1.22.10... (15 files, 5MB)
Uninstalling /usr/local/Cellar/nodenv/1.4.0... (34 files, 105.7KB)
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % sudo rm -rf /usr/local/include/node
Password:
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew link --overwrite node
Error: No such keg: /usr/local/Cellar/node
```

**Comment by monfresh** [comment] 2021-01-30 22:42
Sorry, I should have specified to ignore that last command. Let's continue with these:

```sh
rm /usr/local/lib/libavcodec.56.dylib
rm /usr/local/lib/libavformat.56.dylib
rm /usr/local/lib/libavutil.54.dylib
rm /usr/local/lib/libswresample.1.dylib
brew upgrade
```
and then `brew doctor`

**Comment by juliajoo** [comment] 2021-01-30 23:08
Okay, then I get these results: 
```
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % rm /usr/local/lib/libavcodec.56.dylib
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % rm /usr/local/lib/libavformat.56.dylib
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % rm /usr/local/lib/libavutil.54.dylib
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % rm /usr/local/lib/libswresample.1.dylib
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew update
Updated 3 taps (homebrew/core, homebrew/cask and caskroom/cask).
==> Updated Formulae
gd                         llvm                       proteinortho
include-what-you-use       n                          tfenv
jpeg-xl                    pmd                        topgrade
lf                         procs
==> Updated Casks
evernote                   lx-music                   privatevpn
evernote                   lx-music                   privatevpn
jump                       marvel                     proclaim
jump                       marvel                     proclaim
kode54-cog                 marvin                     profind
kode54-cog                 marvin                     profind
kodelife                   nordvpn                    pushplaylabs-sidekick
kodelife                   nordvpn                    pushplaylabs-sidekick
Jjoo@bagjuyeong-ui-MacBook-Pro ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have the following deprecated, cask taps tapped:
  caskroom/cask
Untap them with `brew untap`.

Warning: The following directories do not exist:
/usr/local/Frameworks

You should create these directories and change their ownership to your user.
  sudo mkdir -p /usr/local/Frameworks
  sudo chown -R $(whoami) /usr/local/Frameworks

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  sass
  python@3.9

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```
Do I have to anything before running `laptop` again in my computer?

**Comment by monfresh** [comment] 2021-01-30 23:55
Yes, `brew upgrade`, not `update`. Then let's try this:

```sh
brew uninstall chruby ruby-install
rm -rf ~/.rubies
```
Quit and restart Terminal.

Then run the script again:
```sh
laptop
```

**Comment by juliajoo** [comment] 2021-01-31 16:20
Oh, my mistake. I ran brew upgrade and it went well in general but at the end I got this error. Is this error ignorable?
![image](https://user-images.githubusercontent.com/22519671/106390398-8e8b7a00-63e8-11eb-95c6-db5be1053305.png)

**Comment by monfresh** [comment] 2021-01-31 18:22
I think we can ignore this for now. Let's try the rest of the steps.

**Comment by juliajoo** [comment] 2021-01-31 18:47
Okay. I followed the above steps and I still get this error. Here is the laptop.log as well.
[laptop.log](https://github.com/monfresh/laptop/files/5900443/laptop.log)


```
>>> Successfully installed ruby 2.7.2 into /Users/Jjoo/.rubies/ruby-2.7.2

Updating Rubygems...
dyld: lazy symbol binding failed: Symbol not found: _rb_deprecate_constant
  Referenced from: /Users/Jjoo/.gem/ruby/2.7.2/gems/etc-1.2.0/lib/etc.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_deprecate_constant
  Referenced from: /Users/Jjoo/.gem/ruby/2.7.2/gems/etc-1.2.0/lib/etc.bundle
  Expected in: flat namespace

mac: line 279: 18417 Abort trap: 6           gem update --system
failed
```

**Comment by monfresh** [comment] 2021-01-31 19:44
I just noticed the `~/.gem` path. Try removing these lines from your `~/.zshrc`:

```
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"
```
Then quit and restart Terminal.
Then run `laptop` again.

**Comment by juliajoo** [comment] 2021-01-31 20:44
It gives me the same error... Do you know what is going on?
[laptop.log](https://github.com/monfresh/laptop/files/5900605/laptop.log)

**Comment by monfresh** [comment] 2021-02-01 01:17
All I know for sure is that your computer is in a bad state due to things you might have tried and installed in the past. So far, I've been trying small changes at a time to narrow things down. Now I'm pretty sure the issue is with your `~/.gem` directory. I just installed a clean copy of Catalina on my spare laptop, and I can confirm that the `~/.gem` directory is not preinstalled by Apple, so we can safely remove it.

Let's try these steps:

Open your `~/.zshrc` file:
```sh
open ~/.zshrc
```
Then **replace** the contents of your `~/.zshrc` file with the text below. Don't run the commands below in your Terminal. Copy and paste them into your `.zshrc` file:
```
alias laptop='bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)'

export PATH="$HOME/.bin:$PATH"

source /usr/local/share/chruby/chruby.sh

source /usr/local/share/chruby/auto.sh

chruby ruby-2.7.2

eval "$(nodenv init -)"
```
Then save the file, and quit and restart your Terminal.
Then let's remove Ruby and the .gem directory:

```sh
rm -rf ~/.gem
rm -rf ~/.rubies
```
Then run the script again:
```
laptop
```

**Comment by juliajoo** [comment] 2021-02-01 13:14
Oh my godness. It finally worked. Thank you so much for helping me and not giving up on my computer. I installed nodenv even though the terminal said it already existed like shown below:
```
nodenv: /Users/Jjoo/.nodenv/versions/14.15.4 already exists
continue with installation? (y/N) y
```
Would this be a problem? 
[laptop.log](https://github.com/monfresh/laptop/files/5904101/laptop.log)

**Comment by monfresh** [comment] 2021-02-01 16:09
Yay! No, the nodenv installation should not be a problem. Now can you try your Jekyll site? Also, make sure to create a file called `.ruby-version`  at the root of your Jekyll folder and paste `ruby-2.7.2` in it. That way, you will automatically have Ruby 2.7.2 when you `cd` into your Jekyll directory. More details here: https://github.com/monfresh/laptop#how-to-switch-between-ruby-versions-and-install-different-versions

**Comment by juliajoo** [comment] 2021-02-01 22:48
Yes!! It succeeded making it work in my local git repository. Thank you soooo much..! 
Lastly may I ask you two more concerns, regarding this? 
(1) Now in my local git repository, when I run bundle exec jekyll serve then, I can see my website is deploying locally. But I got these messages before deploying it like below. 

```
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install 

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme 

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811 
```
Are these advices really crucial for my jekyll to run or is it neglectable?

(2) Although it ran in my local git repository, when I run its fresh clone, then I get this error message again. Do you perhaps have any idea what is going on? 

```
Jjoo@bagjuyeonguimbp youngdesign-master % bundle exec jekyll serve
Configuration file: /Users/Jjoo/Downloads/youngdesign-master/_config.yml
            Source: /Users/Jjoo/Downloads/youngdesign-master
       Destination: /Users/Jjoo/Downloads/youngdesign-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
jekyll 3.8.5 | Error:  No such file or directory @ rb_sysopen - /Users/Jjoo/Downloads/youngdesign-master/bin/gulp
Traceback (most recent call last):
        42: from /Users/Jjoo/.rubies/ruby-2.7.2/bin/bundle:23:in `<main>'
        41: from /Users/Jjoo/.rubies/ruby-2.7.2/bin/bundle:23:in `load'
        40: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
        39: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        38: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
        37: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
        36: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        35: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
        34: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        33: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        32: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        31: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:494:in `exec'
        30: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
        29: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
        28: from /Users/Jjoo/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
        27: from /Users/Jjoo/.gem/ruby/2.7.2/bin/jekyll:23:in `<top (required)>'
        26: from /Users/Jjoo/.gem/ruby/2.7.2/bin/jekyll:23:in `load'
        25: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
        24: from /Users/Jjoo/.gem/ruby/2.7.2/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        23: from /Users/Jjoo/.gem/ruby/2.7.2/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        22: from /Users/Jjoo/.gem/ruby/2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        21: from /Users/Jjoo/.gem/ruby/2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        20: from /Users/Jjoo/.gem/ruby/2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        19: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        18: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
        17: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
        16: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
        15: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
        14: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
        13: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
        12: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/site.rb:69:in `process'
        11: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/site.rb:164:in `read'
        10: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:16:in `read'
         9: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:51:in `read_directories'
         8: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:76:in `retrieve_dirs'
         7: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:76:in `each'
         6: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:80:in `block in retrieve_dirs'
         5: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:45:in `read_directories'
         4: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:45:in `select'
         3: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/reader.rb:46:in `block in read_directories'
         2: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/utils.rb:146:in `has_yaml_header?'
         1: from /Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/utils.rb:146:in `open'
/Users/Jjoo/.gem/ruby/2.7.2/gems/jekyll-3.8.5/lib/jekyll/utils.rb:146:in `initialize': No such file or directory @ rb_sysopen - /Users/Jjoo/Downloads/youngdesign-master/bin/gulp (Errno::ENOENT)
```

**Comment by monfresh** [comment] 2021-02-03 01:38
Hi. Now that your Ruby environment is working, I'm going to close this issue. I'd like to keep issues here related to my script and setting up Ruby. If you need further help with Jekyll, feel free to email me, or ask on the Jekyll forum: https://talk.jekyllrb.com

For the Sass warning, that's because you're using an old version of Jekyll. The latest is 4.2.0. You can always check for the latest version on the  Rubygems site: https://rubygems.org/gems/jekyll/. You can also run `bundle outdated` to see all your outdated gems and their latest versions. 

It's possible there are things in your site and the Barber theme you're using that aren't compatible with the latest Jekyll. Try it and see if it still works. If not, you can go back to what you had, and it shouldn't cause any issues if all you're doing is adding new posts to your site. Here's a guide that might be helpful for working with Gemfiles:

https://www.moncefbelyamani.com/the-beginner-s-guide-to-bundler-and-gemfiles/

For the second issue, I'll let you try to figure it out on your own. Here are some questions I would ask to troubleshoot:

- Where did `bin/gulp` come from?
- Does it exist on the [barber-jekyll](https://github.com/samesies/barber-jekyll) repo? 
- If not, how did it appear in your repo? 
- Did you perhaps add it? If so, why?
- What happens if you remove it?

**Closed by monfresh** 2021-02-03 01:38 UTC
